/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    GraphViz: typeof import('./src/components/GraphViz.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconReputationToken: typeof import('./src/components/IconReputationToken.vue')['default']
    TheDashboard: typeof import('./src/components/TheDashboard.vue')['default']
  }
}
